### ISSUE TITLE
[BUG] main_process_ip not working

### ISSUE THREAD

**Issue by asdfry** [microsoft/DeepSpeed#5136]
**Describe the bug**
Hi, I'm trying multi-node training with accelerate+deepspeed.
During the broadcast before the start of the training, an error occurred regarding the network interface.
I set 192.168.10.161 in the main_process_ip of the accelerate config, but runner.py targets 192.168.121.122. It is master node's first network interface and that can't communicate between nodes.
Is there a way to set the master_addr used by runner.py in my environment?
I would greatly appreciate your assistance.

**Accelerate config**
```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_hostfile: /root/hostfile
  deepspeed_multinode_launcher: pdsh
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: cpu
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_process_ip: 192.168.10.161
main_process_port: 1040
main_training_function: main
mixed_precision: bf16
num_machines: 2
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
```

**Screenshots**
![issue](https://github.com/microsoft/DeepSpeed/assets/39879672/baf98c6b-3711-48f5-8ad4-b836788cb364)

**ds_report output**
```
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [YES] ...... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
evoformer_attn ......... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.10/dist-packages/torch']
torch version .................... 2.2.0+cu121
deepspeed install path ........... ['/usr/local/lib/python3.10/dist-packages/deepspeed']
deepspeed info ................... 0.12.3, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version ..................... 12.3
deepspeed wheel compiled w. ...... torch 2.2, cuda 12.1
shared memory (/dev/shm) size .... 1.00 GB
```
