### ISSUE TITLE
Does ZeRO++ Work on AMD GPU Mi200?

### ISSUE THREAD

**Issue by unavailableun** [microsoft/DeepSpeed#6795]
When I enable ZeRO++ on MI200, hit below exception:

```
[rank0]:   File "/opt/conda/envs/ptca/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 179, in __init__
[rank0]:     self.parameter_offload = self.initialize_ds_offload(
[rank0]:   File "/opt/conda/envs/ptca/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 427, in initialize_ds_offload
[rank0]:     return DeepSpeedZeRoOffload(module=module,
[rank0]:   File "/opt/conda/envs/ptca/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 122, in __init__
[rank0]:     self._convert_to_zero_parameters(ds_config, module, mpu)
[rank0]:   File "/opt/conda/envs/ptca/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 197, in _convert_to_zero_parameters
[rank0]:     Init(module=module,
[rank0]:   File "/opt/conda/envs/ptca/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 990, in __init__
[rank0]:     self.quantizer_module = CUDAQuantizer()
[rank0]:   File "/opt/conda/envs/ptca/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 761, in __init__
[rank0]:     CUDAQuantizer.quantizer_cuda_module = deepspeed.ops.op_builder.QuantizerBuilder().load()
[rank0]:   File "/opt/conda/envs/ptca/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 508, in load
[rank0]:     return self.jit_load(verbose)
[rank0]:   File "/opt/conda/envs/ptca/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 555, in jit_load
[rank0]:     op_module = load(name=self.name,
[rank0]:   File "/opt/conda/envs/ptca/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1309, in load
[rank0]:     return _jit_compile(
[rank0]:   File "/opt/conda/envs/ptca/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1745, in _jit_compile
[rank0]:     return _import_module_from_library(name, build_directory, is_python_module)
[rank0]:   File "/opt/conda/envs/ptca/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2143, in _import_module_from_library
[rank0]:     module = importlib.util.module_from_spec(spec)
[rank0]:   File "<frozen importlib._bootstrap>", line 565, in module_from_spec
[rank0]:   File "<frozen importlib._bootstrap_external>", line 1173, in create_module
[rank0]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[rank0]: ImportError: /home/aiscuser/.cache/torch_extensions/py39_cpu/quantizer/quantizer.so: cannot open shared object file: No such file or directory
```

ds config:
```
    ds_config:
      zero_optimization:
        stage: 3
        offload_param:
          device: none
          pin_memory: false
        offload_optimizer:
          device: cpu
          pin_memory: false
        overlap_comm: false
        reduce_scatter: true
        reduce_bucket_size: auto
        contiguous_gradients: true
        stage3_gather_16bit_weights_on_model_save: true
        stage3_max_live_parameters: 5000000000.0
        stage3_max_reuse_distance: 1000000000.0
        stage3_prefetch_bucket_size: auto
        stage3_param_persistence_threshold: auto
        zero_hpz_partition_size: 16
        zero_quantized_weights: true
        zero_quantized_gradients: true
      activation_checkpointing:
        partition_activations: true
        cpu_checkpointing: false
      zero_allow_untested_optimizer: true
```

ds_report
```
WARNING:root:Cannot import JIT optimized kernels. CUDA extension will be disabled.
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[93m [WARNING] [0m sparse_attn is not compatible with ROCM
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [92m[OKAY][0m
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [93m[NO][0m ....... [92m[OKAY][0m
fused_adam ............. [93m[NO][0m ....... [92m[OKAY][0m
cpu_adam ............... [93m[NO][0m ....... [92m[OKAY][0m
cpu_adagrad ............ [93m[NO][0m ....... [92m[OKAY][0m
cpu_lion ............... [93m[NO][0m ....... [92m[OKAY][0m
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [93m[NO][0m ....... [93m[NO][0m
fp_quantizer ........... [93m[NO][0m ....... [92m[OKAY][0m
fused_lamb ............. [93m[NO][0m ....... [92m[OKAY][0m
fused_lion ............. [93m[NO][0m ....... [92m[OKAY][0m
inference_core_ops ..... [93m[NO][0m ....... [92m[OKAY][0m
cutlass_ops ............ [93m[NO][0m ....... [92m[OKAY][0m
transformer_inference .. [93m[NO][0m ....... [92m[OKAY][0m
quantizer .............. [93m[NO][0m ....... [92m[OKAY][0m
ragged_device_ops ...... [93m[NO][0m ....... [92m[OKAY][0m
ragged_ops ............. [93m[NO][0m ....... [92m[OKAY][0m
random_ltd ............. [93m[NO][0m ....... [92m[OKAY][0m
[93m [WARNING] [0m sparse_attn is not compatible with ROCM
sparse_attn ............ [93m[NO][0m ....... [93m[NO][0m
spatial_inference ...... [93m[NO][0m ....... [92m[OKAY][0m
transformer ............ [93m[NO][0m ....... [92m[OKAY][0m
stochastic_transformer . [93m[NO][0m ....... [92m[OKAY][0m
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/envs/ptca/lib/python3.9/site-packages/torch']
torch version .................... 2.3.0+rocm6.0
deepspeed install path ........... ['/opt/conda/envs/ptca/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.14.4, unknown, unknown
torch cuda version ............... None
torch hip version ................ 6.0.32830-d62f6a171
nvcc version ..................... None
deepspeed wheel compiled w. ...... torch 2.3, hip 6.0
shared memory (/dev/shm) size .... 797.00 GB
[2024-11-26 05:15:05,200] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
WARNING:root:Cannot import JIT optimized kernels. CUDA extension will be disabled.
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[93m [WARNING] [0m sparse_attn is not compatible with ROCM`
```
